---
name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    permissions:
      id-token: write
      contents: read
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.26.x]

    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ matrix.go-version }}"

      - uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-muehlbachler-shared-services/data/google-cloud region | CLOUDSDK_COMPUTE_REGION ;
            github-muehlbachler-shared-services/data/google-cloud workload_identity_provider | GOOGLE_WORKLOAD_IDENTITY_PROVIDER ;
            github-muehlbachler-shared-services/data/google-cloud ci_service_account | GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT ;
            github-muehlbachler-shared-services/data/aws region | AWS_REGION ;
            github-muehlbachler-shared-services/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-muehlbachler-shared-services/data/mongodb-atlas public_key | MONGODB_ATLAS_PUBLIC_KEY ;
            github-muehlbachler-shared-services/data/mongodb-atlas private_key | MONGODB_ATLAS_PRIVATE_KEY

      - uses: pulumi/auth-actions@141415910c3beb54e03b48e9057c204c97b956f2 # v2.1.0
        with:
          organization: muhlba91
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:muhlba91

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d # v7
        with:
          command: preview
          stack-name: prod
          refresh: true
        env:
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"

  deploy:
    runs-on: ubuntu-latest
    name: Pulumi Deploy
    permissions:
      id-token: write
      contents: read
    needs:
      - preview
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.26.x]

    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ matrix.go-version }}"

      - uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-muehlbachler-shared-services/data/google-cloud region | CLOUDSDK_COMPUTE_REGION ;
            github-muehlbachler-shared-services/data/google-cloud workload_identity_provider | GOOGLE_WORKLOAD_IDENTITY_PROVIDER ;
            github-muehlbachler-shared-services/data/google-cloud ci_service_account | GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT ;
            github-muehlbachler-shared-services/data/aws region | AWS_REGION ;
            github-muehlbachler-shared-services/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-muehlbachler-shared-services/data/mongodb-atlas public_key | MONGODB_ATLAS_PUBLIC_KEY ;
            github-muehlbachler-shared-services/data/mongodb-atlas private_key | MONGODB_ATLAS_PRIVATE_KEY

      - uses: pulumi/auth-actions@141415910c3beb54e03b48e9057c204c97b956f2 # v2.1.0
        with:
          organization: muhlba91
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:muhlba91

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d # v7
        with:
          command: up
          stack-name: prod
        env:
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"
